exclude_patterns:
 - docs/*
 - tests/*
 - vendor/*
 - phpunit.*
rules:
 git.user_specific_ignored_file:
  enabled: false
 php.debug_statements: # required as this is a debug/dev package
  enabled: false
